# config file for the webbsite

#sitye settings
title:                    QMRITools
description:              >- # this means to ignore newlines until "baseurl:"
                          This website describes the functionality of QMRITools, a toolbox for analysis 
                          of quantitative magnetic resonance imaging data. The package contains 
                          processing tools related to quantitative MRI and spectroscopy of muscle, heart and nerves.
tagline:                  QMRITools for Mathematica
locale:                   "en-US"

#user settings
name:                     "Martijn Froeling"
email:                    m.froeling@gmail.com
#twitter_username: 
github_username:          mfroeling 

#github settings
show_downloads:           true
github:
  zip_url:                https://github.com/mfroeling/QMRITools/releases/download/2.3.1/QMRITools.zip
  tar_url:                https://github.com/mfroeling/QMRITools/releases/download/2.3.1/QMRITools.zip
  owner_url:              https://github.com/mfroeling
  owner_name:             Martijn Froeling, PhD


# theme settings
markdown:                 kramdown
remote_theme:             mmistakes/minimal-mistakes
minimal_mistakes_skin:    "dark"
search:                   true

# website settings
google_analytics:         UA-164529139-1
url:                      http://mfroeling.github.io/QMRITools
baseurl:                  /QMRITools/
repository:               mfroeling/QMRITools
logo:                     "/assets/images/icon.png"

# Build settings

# Outputting
permalink:                /:categories/:title/
paginate:                 5 # amount of posts to show
paginate_path:            /page:num/
timezone:                 # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _posts

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/  

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-github-metadata
  

# configure the webpage  
author:
  name   : "Martijn Froeling"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : ""
  links:
#    - label: ""
#      icon: ""
#      url: ""
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mfroeling"

footer:
  links:
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/ismrm_mrshub"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mfroeling/QMRITools"  

# website pages and posts
defaults:
# _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
#      read_time: true
#      comments: true
#      share: true
#      related: true
# _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
 
# archives 
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
  